### ISSUE TITLE
Relative imports

### ISSUE THREAD

**Issue by Wiz1991** [similar-manga/similar#1]
Fix relative imports and make this a proper module

**Comment by goldbattle** [comment]
I use [goland](https://www.jetbrains.com/go/) and just directly open the repository folder.
My go workspace is someplace else on my computer, but that is just where it downloads dependencies.
The relative imports should be fine, can you tried just doing `go build cache_mangas.go` and seeing if that works from command line?

**Comment by Wiz1991** [comment]
> I use [goland](https://www.jetbrains.com/go/) and just directly open the repository folder.
> My go workspace is someplace else on my computer, but that is just where it downloads dependencies.
> The relative imports should be fine, can you tried just doing `go build cache_mangas.go` and seeing if that works from command line?

I get the following error:
`package cache_mangas is not in GOROOT (/usr/local/go/src/cache_mangas)`

**Comment by Wiz1991** [comment]
I managed to get the scripts working by running git mod init then changing all the ./ imports to url/module. But this can still be fixed to not require this
